### PR TITLE
Issue number  #16  fix

### PR DESCRIPTION
**Pull request by papergirl**
Allows user to tab between fields to enter data.

### CODE REVIEW

**Comment by jzeferino** [comment]
@papergirl thanks for the PR. Will take a look and let you know.

**Comment by papergirl** [comment]
no worries, happy to make any changes per request, relatively new to using gtk so theres probably better ways of doing it.

**Comment by jzeferino** [comment]
At the moment, using Xamarin Studio 6,3 and Addin Maker 1.3.2 the solution (before you PR) doesn't event compile.

@papergirl what version of Xamarin Studio and Addin Maker do you have installed?

screen shot 2017-05-20 at 10 24 48

**Comment by papergirl** [comment]
I'm using  monodevelop 5.10 looking into it this appears to be because they no longer update the package on apt, and have instead moved to using flatpak which I was previously (naively) unaware of, I will correct this.

Looks like from those errors list we need a different task, to make the plugin compatable with 6.*. However looking at Xamarin's site and release notes too attempt identify the breaking changes I also noticed that Xaminin Studio it's self, is no longer going to be developed for mac/windows and they're recommending using the visual studio extension. I don't know where this leaves MonoDevelop (I assume, it will be still developed), but  if you guys use ios or windows primarily, then this plugin won't be very useful to you in the future ;/

**Comment by jzeferino** [comment]
@papergirl yes, the Visual Studio for Mac will probably replace Xamarin Studio. So it would be nice to make this addin work on visual Visual Studio for Mac.

**Comment by papergirl** [comment]
You'd need to confirm the functionality doesn't exist already in other versions of VS on windows it does, (...barring my ideas of editing multiple langs at once...)  and if didn't it  would require a rewrite of all of this barring the resx/file handling stuff. :/

**Comment by jzeferino** [comment]
@papergirl  ATM the VS for mac don't support event resx file editing, so would be nice to port the atual library to run on VS for mac.

**Comment by papergirl** [comment]
OK I've done the work to get it too compile and run under the latest version however I can't do another PR separate from this one :S, Think I should've used different branches for each piece of work :/ I'm relatively new to git .

**Comment by jzeferino** [comment]
@papergirl You used the same branch to fix that issue? I will try to fix that later. Thank you.

**Comment by jzeferino** [comment]
I've tested it and everything seems to be ok.

**Comment by jzeferino** [comment]
@papergirl I've tested it and everything seems to be ok.

**Pull request merged**
